git:
  REPO_URL : 'https://github.com/HarshitSingh-Codes/0T-packer.git'
  REPO_CREDS : 'github-token'
  REPO_BRANCH : 'aws-Immutable-Infra'

packer:
  enable: true
  config_dir: 'packer'
  config_file: '.'